name: Install, lint and test Python app
on:
    pull_request:
      branches:
        - main
        - master
    workflow_dispatch: {}

defaults:
 run:
  working-directory: ./app_python

jobs:
    check-python:
      strategy:
        matrix:
          python: ["3.9", "3.11", "3.13"]
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python }}
                cache: 'pip'
          - name: Install dependencies
            run: |
                pip install -r requirements.txt
                pip install -r requirements.dev.txt
          - name: Run tests
            run: pytest test.py
          - name: Run linter
            run: ruff check .
          - name: Run formatter check
            run: ruff format --check .
        