name: Install, lint and test Python app
on:
    pull_request:
      branches: [ $default-branch ]
      paths:
      - 'app_python/**'
    push:
      branches: [ $default-branch ]
      paths:
      - 'app_python/**'
    workflow_dispatch: {}

defaults:
 run:
  working-directory: ./app_python

jobs:
    check-python:
      name: Run tests and lint
      strategy:
        matrix:
          python: ["3.9", "3.11", "3.13"]
          os: [ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python }}
                cache: 'pip'
          - name: Install dependencies
            run: |
                pip install -r requirements.txt
                pip install -r requirements.dev.txt
          - name: Run tests
            run: pytest test.py
          - name: Run linter
            run: ruff check .
          - name: Run formatter check
            run: ruff format --check .
    security:
      name: Snyk Security Check
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/python-3.10@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            args: --severity-threshold=high --file ./app_python/requirements.txt
          